version: '3'

services:
  mongodb_svc:
    container_name: mongodb_svc
    build: ../services/mongodb
    # image: mongo:5.0.5
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USER=${MONGODB_ROOT_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
    - "45000:27017"
    volumes:
    - ../services/mongodb/data:/data/db
    networks:
    - succotash

  mongo-express:
    container_name: mongo-express_svc
    image: mongo-express
    restart: always
    ports:
    - 45001:8081
    depends_on:
    - mongodb_svc
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USER}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_SERVER=mongodb_svc
    - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - succotash

networks:
  succotash: